import Head from "next/head";
import Footer from "../../src/components/footer/Footer";
import Header from "../../src/components/header/Header";
import { t } from "i18next";
import Product from "../../src/components/product/Product";
import callApi from "../../src/api/callApi";
import { GET_PRODUCT, GET_RELATED_PRODUCT } from "../../src/api/urls";
import { useEffect } from "react";
import { useSelector } from "react-redux";

export default function ProductPage({ product, similar }) {
  const lang = useSelector((state) => state.stateLang.lng);

  return (
    <div>
      <Head>
        <title>
          {lang === "fa" ? product.data.title : product.data.titleEn}
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Product datas={product.data} similar={similar.data} />
      </main>
      <Footer />
    </div>
  );
}
export async function getServerSideProps(context) {
  const { params } = context;
  const { product } = params;
  const data = await callApi(GET_PRODUCT + product, false, "{}", "GET");
  const similar = await callApi(
    `${GET_RELATED_PRODUCT}?Lable=${data.data.lable}`,
    false,
    "{}",
    "GET"
  );
  return {
    props: { product: data, similar: similar }
  };
}
