import Head from "next/head";
import { useTranslation } from "react-i18next";
import callApi from "../../src/api/callApi";
import { GET_ALL_PRODUCT } from "../../src/api/urls";
import Footer from "../../src/components/footer/Footer";

import Header from "../../src/components/header/Header";
import Shop from "../../src/components/shop/Shop";

export default function ShopPage({ shop }) {
  const { t } = useTranslation();
  return (
    <div>
      <Head>
        <title>{t("shop")}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    

      <main>
        <Shop datas={shop.data} />
      </main>
      <Footer />
    </div>
  );
}
export async function getServerSideProps(context) {
  const data = await callApi(GET_ALL_PRODUCT, false, "{}", "GET");
  return {
    props: { shop: data } // will be passed to the page component as props
  };
}
