import Head from "next/head";
import { useTranslation } from "react-i18next";
import AboutUs from "../src/components/aboutUS/AboutUs";
import Footer from "../src/components/footer/Footer";
import OurTeam from "../src/components/ourTeamKarma/OurTeam";

const OurTeamPage = () => {
  const { t } = useTranslation();

  return (
    <div>
      <Head>
        <title>{t("ourTeam")}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <OurTeam />
      </main>
      <Footer />
    </div>
  );
};

export default OurTeamPage;
