import Head from "next/head";
import Footer from "../src/components/footer/Footer";

import Header from "../src/components/header/Header";

import { useTranslation } from "react-i18next";
import UserProfile from "../src/components/profile/UserProfile";
import Placement from "../src/tools/placement/Placement";
import { useSelector } from "react-redux";
import FullScreenLoader from "../src/tools/loader/FullScreenLoader";

export default function ProfilePage() {
  const { t } = useTranslation();
  const user = useSelector((state) => state.stateRegister);

  return (
    <div>
      <Head>
        <title>{t("profile")}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {user.userDataLoader ? (
        <FullScreenLoader />
      ) : !user.loginStatus ? (
        <Placement text={t("firstLogin")} />
      ) : (
        <main>
          <UserProfile />
        </main>
      )}
      <Footer />
    </div>
  );
}
