import Head from "next/head";
import { useTranslation } from "react-i18next";
import callApi from "../../src/api/callApi";
import { GET_ALL_COURSE, GET_COURSE } from "../../src/api/urls";
import AllCourses from "../../src/components/courses/AllCourses";
import Footer from "../../src/components/footer/Footer";
import Header from "../../src/components/header/Header";
export default function CoursesPage({ courses }) {
  const { t } = useTranslation();
  return (
    <div>
      <Head>
        <title>{t("course")}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <AllCourses datas={courses.data} />
      </main>
      <Footer />
    </div>
  );
}
export async function getServerSideProps(context) {
  const data = await callApi(GET_ALL_COURSE, false, "{}", "GET");
  return {
    props: { courses: data } // will be passed to the page component as props
  };
}
